### ISSUE TITLE
Auto Un-Park Functionality

### ISSUE THREAD

**Issue by gomker** [gomker/AirPark#2]
Logic needs review for use cases.
Un-Parking a boat makes sense, but a plane that is mid-flight will crash unless an auto-pilot is enabled.

**Comment by SpannerMonkey** [comment]
I have never fully understood the reasons for the auto un park,  especially as it was originally meant to be used as you say for aircraft,  i think it is really pushing the boundaries of the code to expect a faultless resumption of  a flight if the aircraft is unattended. 
Maybe  there are already combos that would work, such as pilot assistant , as you can tell it to keep a heading and altitude. If you were to  park it and on resume, if engines are back at preset power it will try to stay at the pre sets, I've not tested them together but I will, unless 1 cancels the other out i can't see it being worse than what we have at present.
If that doesn't work, maybe draw a line and clearly state what it can and cannot do, and those things it almost does can be left to users to work out,

**Comment by gomker** [comment]
After seeing how 1.2 behaves we may no longer need AirPark at all. I have not since updating VesselMover.

**Comment by SpannerMonkey** [comment]
while conversely I'm having a world of trouble with ships not staying together on unpack and was just about to see if AP would help alleviate the problem

**Comment by gomker** [comment]
I do have the same stabilization code in the park code as I updated VesselMover. I haven't experienced anything falling apart yet, except my carrier.
